### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by StephanKrauss** [endroid/Twitter#12]
Hello,

i get an exception.
## Here is my script

<?php

include('vendor/autoload.php');

use Endroid\Twitter\Twitter;

// If you want to fetch the Twitter API with "application only" authentication, $accessToken and $accessTokenSecret are optional

// $twitter = new Twitter('aaaaaaaaaaaaaaaaaa', 'bbbbbbbbbbbbbb', 'cccccccccccccc', ' dddddddddddddddddddddd');

// Retrieve the user's timeline
$tweets = $twitter->getTimeline(array(
    'count' => 5
## ));

Exception message:
 Fatal error: Uncaught exception 'Buzz\Exception\RequestException' with message 'SSL certificate problem: unable to get local issuer certificate' in C:\xampp1\htdocs\twitter\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php on line 31

Buzz\Exception\RequestException: SSL certificate problem: unable to get local issuer certificate in C:\xampp1\htdocs\twitter\vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php on line 31

How can help ?

Your sincerly

Stephan

**Comment by Nimesh-Soni** [comment]
Same issue.

"
SSL certificate problem: unable to get local issuer certificate
500 Internal Server Error - RequestException
"

in vendor\kriswallsmith\buzz\lib\Buzz\Client\Curl.php at line 28   -
            $errorMsg = curl_error($this->lastCurl);
            $errorNo  = curl_errno($this->lastCurl);
            $e = new RequestException($errorMsg, $errorNo);
            $e->setRequest($request);
            throw $e;
        }

**Comment by endroid** [comment]
Thanks for your input. Unfortunately I'm still unable to reproduce the issue you are having. Have any of you found the cause and/or a solution in the meantime?

**Comment by creatiombe** [comment]
I fixed the issue in a branch, when you are developing without ssl on your local pc, the curl setVerifyPeer should be set to false, i solved this in a pull request.
