### ISSUE TITLE
Wrong token URL causes an uncaught exception in getBearerHeader()

### ISSUE THREAD

**Issue by cyberhobo** [endroid/Twitter#19]
The token URL is currently built using the BASE_URL constant:

https://github.com/endroid/Twitter/blob/d28a097bf920917ea0aefe7c22df23ed5229ff01/src/Twitter.php#L250

That results in https://api.twitter.com/1.1/oauth2/token, which gives me this error:

`PHP Fatal error:  Uncaught exception 'Endroid\Twitter\Exception\InvalidResponseException' with message 'Twitter response is invalid: ...`

That's followed by the Twitter error page HTML.

If I hard code https://api.twitter.com/oauth2/token it works fine.

Maybe just put the full URL in TOKEN_URL and remove BASE_URL?

**Comment by endroid** [comment]
Hi @cyberhobo this library seriously needs an update to the latest API version. I plan to make a 2.0 release but I don't know when exactly so for now you can best fork it or create a PR to be able to create the base url or maybe even look if there is another library out there that already handles this correctly.
