### ISSUE TITLE
Can't upload media

### ISSUE THREAD

**Issue by fueguino84** [endroid/twitter#20]
I'm getting "media type unrecognized" error from Twitter while using uploadMedia method. I'm testing with a small jpg image.

If I call the query method I'm being able to update my twitter account status, so credentials are ok. I tried also changing the file name to a nonexistant and the error changed (No or invalid file set!), so I think probably there is some issue with the code? Maybe something with Buzz dependencies? Just guessing...

**Comment by endroid** [comment]
Hi @fueguino84 thank you for your question. I am not sure what could be the cause. If you want me to look into it, please attach the image and the code you have written to upload the image so I can try to reproduce it.

FYI: regarding Buzz, I intend on refactoring the library, create a separate bundle for Symfony an move to Guzzle / php-http for the requests but that depends on when I have time to do this.

**Comment by endroid** [comment]
Apparently I get the same errors. In the meanwhile I also switched to a new library for performing the undelying calls: [abraham/twitteroauth](https://twitteroauth.com/) which provides a working implementation and tagged a new version providing a getTimeline and postStatus (with optional media). So if you can upgrade to the new version, the issue should be solved. If you are on an older version of Symfony or PHP, you can also directly use the mentioned library to send your messages and media.
