### ISSUE TITLE
Buzz has deprecated setTimeout()

### ISSUE THREAD

**Issue by sterichards** [endroid/twitter#23]
`request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "setTimeout" of class "Buzz\Client\Curl"." at /var/www/html/vendor/endroid/twitter/src/Twitter.php line 87 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"setTimeout\" of class \"Buzz\\Client\\Curl\". at /var/www/html/vendor/endroid/twitter/src/Twitter.php:87)"}`

**Comment by endroid** [comment]
Hi @sterichards please upgrade to 2.x which does not rely on the setTimeout method.
