### ISSUE TITLE
Type error: Return value of Endroid\Twitter\Client::getTimeline() must be of the type array, object returned

### ISSUE THREAD

**Issue by AdamReece-WebBox** [endroid/twitter#24]
Using version 2.0.4 of this package it appears that there is a return type hint issue with the `getTimeline()` function:

`public function getTimeline(int $count = 25): array`

However an object is being returned, so it causes an error:

> Type error: Return value of Endroid\Twitter\Client::getTimeline() must be of the type array, object returned

This appears to happen because I've given the wrong API credentials, but the `getTimeline()` function should be throwing an exception instead of trying to return an object. (Or cast the object to an array.)

**Comment by AdamReece-WebBox** [comment]
Giving the `TwitterOAuth` instance the 2 additional (but optional) access token parameters resolved this for me, and I now get an array back, but the function in this package should still be fixed.

**Comment by endroid** [comment]
Thank you @AdamReece-WebBox. I see the client library indeed has multiple possible return types :) I now added a check if the client returns a valid response and otherwise throw an exception.

**Comment by AdamReece-WebBox** [comment]
Excellent, thank you @endroid
