### ISSUE TITLE
Proxy does not work

### ISSUE THREAD

**Issue by anthonyherve** [endroid/Twitter#9]
Hello,

I want to use parameter proxy in EndroidTwitterBundle but I have this error : 
_Attempted to call an undefined method named "setProxy" of class "Buzz\Client\Curl"._

I think it's caused by version of "kriswallsmith/buzz": "^0.6".

Can you please increase this version to the latest stable 0.15 ?

Thank you.

**Comment by endroid** [comment]
Hi @anthonyherve I increased the minimum version so the setProxy call is available. As the version 0.6 mentioned in the composer.json is only a minimum requirement you can always enforce a more recent version yourself by explicitly requiring the buzz library with the desired version. As long as you require a version higher than 0.6 it should not conflict with this Twitter library.
